version: '3' 
services:
# Postgres database
  postgres:
      image: 'postgres:latest'
      environment:
        - POSTGRES_PASSWORD=postgres_password
        - POSTGRES_DB=simple_blog_api
#Simple Blog API
  api:
      depends_on:
        - postgres
      image: sdevpura/simple_blog_api_ts-master-api:latest
      build: .
      environment:
        - POSTGRES_HOST=postgres
        - POSTGRES_PORT=5432
        - POSTGRES_USERNAME=postgres        
        - POSTGRES_PASSWORD=postgres_password
        - POSTGRES_DB=simple_blog_api
      ports:
        - "3000:3000"